### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by atomGit** [Ximi1970/systray-x#102]
installing the .xpi prompts that it has access to the entire OS and this seems quite dangerous

am i missing something?

Manjaro Linux, KDE

**Comment by Ximi1970** [comment]
![image](https://user-images.githubusercontent.com/859953/135727657-1e96e8a9-c908-42b5-bd91-e71b841ff3aa.png)

You mean this message from TB?
Every program you install can potentially access all your data. Even your OS.

Be aware that before TB 61 full access was standard for all the add-ons.
But nowadays the message is triggered by requesting the experimental APIs to get full access in the manfest.json.

I need full access to count the unread messages because there is no API controlled by TB (untill TB 91) to do that.
I also need full access to control the TB close button. also because there is no API implemented.

The code is opensource so you can check it yourself.

**Comment by atomGit** [comment]
yes, that is the prompt - thanks for your explanation
