### ISSUE TITLE
TB window is minimized on change of workspace

### ISSUE THREAD

**Issue by dreisieben** [Ximi1970/systray-x#137]
**Describe the bug**
I have TB running on its own workspace in gnome. When I switch to another workspace (using a keyboard shortcut)  and then return to TB's workspace, the TB window is minimized. (Same behavior in X11 and wayland.)

**To Reproduce**
Use multiple workspaces in gnome. Open TB on one workspace. Switch to another workspace using the keyboard shortcut for switching workspaces. Return to the workspace on which the TB window should be open. However, TB window is minimized.

**Expected behavior**
TB window should be open.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 36)
 - Architecture: x86_64
 - Desktop type / Window Manager: Gnome 42
 - Thunderbird version and arch: TB 102.4.1, 64 bit
 - Run `echo $XDG_SESSION_TYPE` in a terminal and report the results: x11
 - Add-on version: 0.9.2
 - App version: 0.9.2
 - Install type: TB-addon / App: Fedora rpm package   
 - Used Qt library:  default system repository (version 5.15.6)

**Additional context**
N/A

**Comment by JerwuQu** [comment]
For me on i3, setting the "Minimize" action in systray-x settings to "Default minimize" rather than "Minimize to tray" prevents this behavior, but then I cannot close the window instead because the "Close" action doesn't minimize to tray.

I think a solution could be to have another option for "Close" which does the same minimization as the "Minimize to tray" option under "Minimize" does.

**Comment by Ximi1970** [comment]
Solved after refactor of window handling. Available in git, develop. Not yet in a release
