### ISSUE TITLE
Support the new version of Thunderbird 115.0+

### ISSUE THREAD

**Issue by giwrgosmant** [Ximi1970/systray-x#147]
**Describe the bug**
The current version of systray-x is incompatible with the new release of Thunderbird 115.0+.

**Desktop (please complete the following information):**
 - OS: Windows
 - Architecture: 64 bit
 - Thunderbird version and arch: 115.0 (64-bit)
 - Add-on version: 0.9.2
 - App version: 0.9.2

**Comment by Antiz96** [comment]
For information, I opened a related pull request: #148

**Comment by Antiz96** [comment]
Well, [support for Thunderbird 115+ has been added](https://github.com/Ximi1970/systray-x/commit/d32a4fdfe12bbfdec38564b4c5b34345e05dd108) and [a new tag has been created](https://github.com/Ximi1970/systray-x/releases/tag/0.9.3).
My pull request has been ignored though, I guess I'll just close it ^^

This issue can be closed as treated however :)

**Comment by Ximi1970** [comment]
Addon is now allowing even 116. Seems it all still works (just a quick test)
Released a new version.

**Comment by Ximi1970** [comment]
Had problems upgrading in Windows a year ago. Thought I sovled it....
Will have a look again.
Please try this:

https://github.com/Ximi1970/systray-x/issues/106#issuecomment-942025138

**Comment by Ximi1970** [comment]
I saw the icon change to late...
I will update the icon and double check the Windows installer script.

**Comment by koroki** [comment]
Simply, thanks for the update.
Works properly in Arch linux + gnome (thunderbird working in xwayland).

**Comment by Antiz96** [comment]
@Ximi1970 Do you mind creating a new tag so new binaries can be built including the new icon?

**Comment by Ximi1970** [comment]
New version with new the icon for >115 and separate actions are possible now for minimize, close and icon click.

**Comment by Antiz96** [comment]
@Ximi1970 Thanks, works as expected on Arch!

**Comment by Ximi1970** [comment]
Needed to update my VMs a bit, but Windows 11 works  just fine with a clean install.
The old installer was a bit of a disaster, sorry..., and cannot be uninstalled if you used the single user install.
 You need to manually remove the SysTray_X directory from the C:\Users\<user>\AppData\Local\Programs\ dir and
 remove the addon in Thunderbird in the Add-ons and Themes, extensions dialog.
 Then you can use the new installer.

**Comment by DSDV** [comment]
when i want to install this addon on fedora 38 it wants to install thunderbird (102) as well. 
But thunderbird 115 (flatpack is already installed and running :( 

i think something is not working

**Comment by Ximi1970** [comment]
Please upgrade your addon to version 0.9.4. I am not able to block installing a newer TB version under Windows(tm)(c) because the addon does not support it. Most of the time it is just that I did not check the functionality yet and released a new version.

**Comment by DSDV** [comment]
![image](https://github.com/Ximi1970/systray-x/assets/5504857/4a71ea42-e02b-4251-86d4-40c14dc8180b)
@Ximi1970 my problem seems reversed :/

**Comment by Ximi1970** [comment]
No your problem is using flatpak. This is a sandboxed TB application and probably will not work with an externally installed TB addon. The flatpak is not registered by the system and does not use the system dependency to operate.
If you really want to use a flatpak contruction you need a flatpak with TB and an installed systray-x addon.

But may I ask why you are using a flatpak while there is a perfectly working TB in the repository?

**Comment by DSDV** [comment]
Oh so systray-x is not compatible with flatpak?

`But may I ask why you are using a flatpak while there is a perfectly working TB in the repository?`
because its flatpak? Thunderbird is not a program which needs some deep system access like my kvm/qemu. 
Therefor its going to be a flatpak. If you ask the question of direct install vs flatpak i dont want to derail this issue into a apple/android war scenario ;) 
For me personally everything not requiring deep system level access has to be a flatpak which i than additionally can control with flatpak seal (:

**Comment by Ximi1970** [comment]
No, flatpak is not compatible with SysTray-X.
Tried to install the addon manually. The addon installed without any problems but TB can not find the companion app.
The TB flatpak will not read the default "native-messaging-hosts" directories anywhere on the system. Not in /usr/lib64/mozilla, not in the user dir ~/.mozilla and not in the flatpak dirs ~/.var/app/org.mozilla.firefox (or app/org.mozilla.Thunderbird which is not standard).
The TB flatpak is not compatible with the native messaging / application api of mozilla itself.
If you can find the right directory, please let me know.
