### ISSUE TITLE
Support for Thunderbird 128 Nebula?

### ISSUE THREAD

**Issue by panyann** [Ximi1970/systray-x#197]
**Is your feature request related to a problem? Please describe.**
The described way of adding the Thunderbird PPA installs the Thunderbird 115, instead of the latest version.

**Describe the solution you'd like**
Is it possible to install Thunderbird 128 and use it with this extension?

**Comment by Ximi1970** [comment]
The plugin works fine with TB < 131...

It lookes like all the distributions find the latest "release" 128 not very trustworthy and are not generating package for this release yet.

According to Betterbird:

`
Note that Thunderbird 128 and hence Betterbird 128 is shipping with a broken backend causing IMAP folder corruption under some circumstances. Some Thunderbird users report that they need to repair they IMAP mailboxes multiple times per week. Hence version 128 SHOULD NOT BE USED IN PRODUCTION!!

For details please follow [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1890230). Note that since the Thunderbird folks forced version 128.0.1 onto unsuspecting users, they are getting a high volume of reports that people's e-mail can't be displayed any more.

We estimate that version 128.3.0 may be safe to use.
`

You have been warned!

If you really want to live on the edge and risk scrambling all your mail, install the standard thunderbird version and systray-x first, then manually add the add-on in the newer TB by using the "install add-on from file" option in the "Add-ons and themes" dialog of TB.
You can find the XPI here:

```
/usr/share/doc/packages/systray-x/systray-x@Ximi1970.xpi
```

This will only work for the TB <= 130.xxx betas but only if they do not change to much.
As soon as they move to TB 131, this will not work anymore.
You need to update the TB version in the manifest json and compile the git repository yourself in that case.

**Comment by Ximi1970** [comment]
The Windows Systray-X installer will always install but will only work with hardcoded TB version limitations at the moment of release. (0.9.10 -> TB91 -> TB130)

**Comment by panyann** [comment]
@Ximi1970 Thank you for a detailed response, I really appreciate it!

In this case I will probably stay with 115.14 for now and wait for the update, but we'll see.
However that's strange what you say, they ship a Thunderbird flatpak with 128.1.1 and snap with 128.1.0 and they do that unsafely? 🤔

BTW great extension, I have totally no errors using it and I had various problems with the Birdtray.

**Comment by panyann** [comment]
I'll just add info for anyone interested.
You can add PPA ppa:mozillateam/thunderbird-next. It includes beta versions of Thunderbird.
At the moment there is no version 128 there yet, but 125.
It works correctly with the systray-x.
