### ISSUE TITLE
Cannot install it

### ISSUE THREAD

**Issue by GeorgeKaragiannis** [Ximi1970/systray-x#67]
Hello, I have a problem with the installation. What can I do to fix it?

Thunderbird: 68.12.0 (64bit)

Distro: MX-19.3_x64 patito feo February 15  2020
Kernel: 4.19.0-6-amd64 x86_64
Desktop: Xfce 4.14.2

The problem:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 systray-x-minimal : Depends: thunderbird (<= 1:84) but 2:68.12.0-1mx19+1 is to be installed
E: Unable to correct problems, you have held broken packages.**

**Comment by Ximi1970** [comment]
Have a look here: https://github.com/Ximi1970/systray-x/issues/61#issuecomment-735898689

**Comment by GeorgeKaragiannis** [comment]
@Ximi1970  So, the problem is that I have an old version (68) and I need the new one (78)?

**Comment by Ximi1970** [comment]
No, someone at MX thought he was smart and started to use epoch number 2 for the Thunderbird package. (probably because they made some major modification to it) and it is just impossible to create 1 Debian package that will accept epoch 1 (Debian) and epoch 2 (MX) Thunderbird dependencies.   
I also do not have access to a build service to create a special MX packages.  
Thunderbird is already a software mess and if MX is also changing things in TB it gets really complicated. That is the reason I will not support MX directly.    
You need to use the workaround I mentioned.  
It should also work with a Debian 1:68.x.x  version if you can find one.

**Comment by GeorgeKaragiannis** [comment]
@Ximi1970 Thank you again. One last thing. MX linux boots with the sysVinit init system by default, but if you want, there is the option to start it with the systemd, so you can choose. Is this "epoch number" has to do anything with this? If I chose systemd, will it work or it doesn't matter?

**Comment by Ximi1970** [comment]
The epoch package version number is a "choice" of the Thunderbird MX package maintainer and normally should not be incremented unless really needed to prevent dependency problems or mark a major change in the package.  
You or I cannot change anything to make it "right" or undo the epoch version number of the MX Thunderbird package except for creating your own Thunderbird package with epoch version number 1.  Or make a MX package for SysTray-X with a dependency on Thunderbird 2:68.x.x to 2:85.x.x.

**Comment by GeorgeKaragiannis** [comment]
Thank you very much!
