### ISSUE TITLE
close button works once but no more ^^

### ISSUE THREAD

**Issue by stef942** [Ximi1970/systray-x#73]
just a small bug in 0.7 gnome: the close button works once but no more when the thunderbird window is reopened, minimize works.

**Comment by Ximi1970** [comment]
Please start your bug report mentioning at least:

    OS and architecture used (32 or 64 bit)
    Desktop / Window Manager (KDE, Xfce, Cinnamon, MATE etc)
    Thunderbird version and arch (32 or 64 bit)
    Add-on version
    App version
    Install type: github repository build, script installer, OBS repository.
    Used Qt library (default system repository, other OBS repo, self-compiled, Qt online installer)

Bug description, how to reproduce, what you expect to happen.

Thank you for reporting!
@Ximi1970

**Comment by Ximi1970** [comment]
I got 20+ different setups I would need to check....

**Comment by askembris** [comment]
I have a similar issue that may be related. I have created a custom shortcut in KDE to make Thunderbird's window appear (it used to be the command to run TB with a flag to toggle fireTray, now it just runs /usr/bin/thunderbird to make the window appear). 

With SysTray-X, the window appears fine (but is not toggled - would be great if you could create a keyboard shortcut for that!)

From version 0.7 onward, if I make the window appear using the keyboard shortcut, then the "close" button stops working, only "minimise" works. If I recall the window by clicking on the tray button, then the close button works normally. 

In my work PC, same setup but a few versions back on KDE and SysTray-X, "close" works normally regardless of how TB's window is made to appear. 

The PC with the issue is running TB 78.6.1, SysTray-X 0.7.0, and Plasma 5.20.5. The office PC (which works fine) is a few versions prior to those (not more than 2 months) - I think SysTray-X is 0.6.7 in that case but I am not too certain. Both on OpenSUSE Tumbleweed with the RPM straight from the repo. 

I can live with using "minimise", but I have gotten kinda used to going for "close". A keyboard shortcut (I use Alt-T) to toggle the window between normal and minimised to tray would be the best option.
